ALTER TABLE "Doctor"
ADD COLUMN "givenName" TEXT,
ADD COLUMN "secondaryName" TEXT,
ADD COLUMN "familyName" TEXT,
ADD COLUMN "noFamilyName" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "gender" TEXT,
ADD COLUMN "dateOfBirth" TEXT,
ADD COLUMN "phoneCode" TEXT DEFAULT '+91',
ADD COLUMN "phone" TEXT,
ADD COLUMN "address" TEXT,
ADD COLUMN "experienceRange" TEXT,
ADD COLUMN "qualification" TEXT,
ADD COLUMN "practitionerType" TEXT,
ADD COLUMN "services" TEXT,
ADD COLUMN "about" TEXT,
ADD COLUMN "ahpraNumber" TEXT,
ADD COLUMN "prescriberNumber" TEXT,
ADD COLUMN "providerNumber" TEXT,
ADD COLUMN "hpiIndividualNumber" TEXT,
ADD COLUMN "hpioNumber" TEXT,
ADD COLUMN "saveMyHINumber" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "mimsUserId" TEXT,
ADD COLUMN "mimsEulaAccepted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "mimsTermsAccepted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "prescriptionEntityId" TEXT,
ADD COLUMN "prescriptionAccessEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "accountHolderName" TEXT,
ADD COLUMN "accountNumber" TEXT,
ADD COLUMN "routingNumber" TEXT,
ADD COLUMN "autoDraftNotesEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "otpDeliveryChannel" TEXT NOT NULL DEFAULT 'BOTH';