"""Initial schema

Revision ID: 215ba7420c86
Revises: 
Create Date: 2026-06-11 14:34:13.981302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '215ba7420c86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverage_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_species', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_cost', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=False),
    sa.Column('common_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('taxonomy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('habitat', sa.String(), nullable=True),
    sa.Column('geographic_range', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diet_type', sa.String(), nullable=True),
    sa.Column('conservation_status', sa.String(), nullable=True),
    sa.Column('population_trend', sa.String(), nullable=True),
    sa.Column('lifespan_years', sa.String(), nullable=True),
    sa.Column('weight_kg', sa.String(), nullable=True),
    sa.Column('length_cm', sa.String(), nullable=True),
    sa.Column('behavior', sa.String(), nullable=True),
    sa.Column('reproduction', sa.String(), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('wikipedia_url', sa.String(), nullable=True),
    sa.Column('sources_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('field_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_filled_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_scientific_name'), 'species', ['scientific_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_species_scientific_name'), table_name='species')
    op.drop_table('species')
    op.drop_table('pipeline_runs')
    op.drop_table('coverage_reports')
    # ### end Alembic commands ###
